### ISSUE TITLE
After logging in for the first time, I received an error about a missing index

### ISSUE THREAD

**Issue by sfc-gh-nrockson** [uidude/minders#8]
The error is copy/pasted below:

```
The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/minders-654fd/firestore/indexes?create_composite=Ckxwcm9qZWN0cy9taW5kZXJzLTY1NGZkL2RhdGFiYXNlcy8oZGVmYXVsdCkvY29sbGVjdGlvbkdyb3Vwcy9taW5kZXIvaW5kZXhlcy9fEAEaCwoHcHJvamVjdBABGgkKBXN0YXRlEAEaDQoJdXBkYXRlZEF0EAIaDAoIX19uYW1lX18QAg

Component stack:
    at MinderList (http://localhost:19006/static/js/bundle.js:11726:86)
    at Minders (http://localhost:19006/static/js/bundle.js:14008:27)
    at ComponentWithLoad (http://localhost:19006/static/js/bundle.js:3313:103)
    at div
    at http://localhost:19006/static/js/bundle.js:211740:25
    at Suspense
    at TriState (http://localhost:19006/static/js/bundle.js:2265:81)
    at div
    at http://localhost:19006/static/js/bundle.js:211740:25
    at div
    at http://localhost:19006/static/js/bundle.js:211740:25
    at KeyboardAvoidingView (http://localhost:19006/static/js/bundle.js:206786:81)
    at div
    at http://localhost:19006/static/js/bundle.js:211740:25
    at SafeAreaView (http://localhost:19006/static/js/bundle.js:204511:25)
    at Layout (http://localhost:19006/static/js/bundle.js:10141:24)
    at Scope (http://localhost:19006/static/js/bundle.js:2427:25)
    at ApplyLayout (http://localhost:19006/static/js/bundle.js:9397:22)
    at http://localhost:19006/static/js/bundle.js:6318:90
    at StaticContainer (http://localhost:19006/static/js/bundle.js:53547:16)
    at EnsureSingleNavigator (http://localhost:19006/static/js/bundle.js:53120:23)
    at SceneView (http://localhost:19006/static/js/bundle.js:53440:21)
    at div
    at http://localhost:19006/static/js/bundle.js:211740:25
    at div
    at http://localhost:19006/static/js/bundle.js:211740:25
    at div
    at http://localhost:19006/static/js/bundle.js:211740:25
    at CardSheet (http://localhost:19006/static/js/bundle.js:63072:22)
    at div
```

**Comment by sfc-gh-nrockson** [comment]
This is the UI when I follow the above URL:

<img width="446" alt="image" src="https://github.com/uidude/minders/assets/129793256/301bf1ca-2d2f-40b2-8df7-5b73e4de2ff9">

It seems that we need an index over:

```
project
state
updatedAt
__name__
```
